version: '3'

services:

  testwebapi:
    build:
      context: ../
      dockerfile: ./TestWebApi/Dockerfile-Local-Debug
    ports:
      - "5000:80"
    environment:
      NODE_ENV: development
    networks:
      - tasslenet

networks:

  tasslenet:
    driver: bridge
